name: Website Monitor

on:

  schedule:
    - cron: '0 3 * * *'
    - cron: '0 13 * * *'

  workflow_dispatch:

jobs:

  monitor:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5

      with:
        python-version: '3.13'

    - name: Install Requirements
      run: pip install -r requirements.txt

    - name: Run Website Monitor

      env:
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}

      run: python check.py